### ISSUE TITLE
Frontend issues for old users after upgrading to 22.09

### ISSUE THREAD

**Issue by amarkulo** [Countly/countly-server#3865]
I have upgraded Countly from 20.x version to 22.x version and I had few issues now with it. 

I'm using docker image and I created new docker environment, created global admin user and then restored mongodb dump that I made previously. So far so good, everything works, but I cannot administer users in dashboard.  I can see all users, create new one, but can't edit or delete user. Updating and deleting them from API works as it should.

This is the first part of the problem. The second part is that if I log in with any of the old users, dashboard is not working for them at all. In the developer console there is load of TypeError: this.sortBy is not a function, left hand side menu cannot be open, it just blinks on open, etc. If the user is global admin, he cannot see anything in management sidebar, etc.

While testing I have tried all 22.x versions and all had the same "user bug" for me. So my thought process was that I will create new instance, import the app data and it will be fine and it was until I logged in with the old admin user, so it's definitely something user related stored in the database.

Here are few screenshots in case they can help.

![Screenshot 2023-01-20 094203](https://user-images.githubusercontent.com/398525/213663340-7113d417-3795-4b3d-aa9a-af79880634c1.png)

![Screenshot 2023-01-20 094223](https://user-images.githubusercontent.com/398525/213663344-1ac47a0e-7cc9-4220-88f7-4b1218000698.png)

I have recreated users and solved my problem this way, but still I would like to understand what was the issue for future reference.

### Your Environment
* Operating System and version: Docker environment created with docker-compose on Ubuntu 20.04 LTS
* Any changes you have made to your instance:  none

**Comment by ar2rsawseen** [comment]
Hello,
It sounds like old users were not converted to the new permission system.
Did you run the upgrade scripts from here:
https://github.com/Countly/countly-server/tree/master/bin/upgrade

**Comment by amarkulo** [comment]
Hello Arturs!

Yes, I have run upgrade script according to the manual after upgrading in a frontend container.

`bash -c "/opt/countly/bin/docker/postinstall.sh; bash /opt/countly/bin/upgrade/22.09/upgrade_db.sh combined"`

**Comment by ar2rsawseen** [comment]
I see, so if you are upgrading from 20.x version to 22.x version you would need to run all scripts in between as described here:
https://support.count.ly/hc/en-us/articles/360037443652-Upgrading-the-Countly-Server#skipping-versions-when-upgrading
